# -*- coding: utf-8 -*-
"""Agents_Streaming.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qmo86t5NCJeFTD73v2ftDQu7YqJ4Hig7
"""

!pip install openai-agents

import nest_asyncio
nest_asyncio.apply()

from agents import Agent, Runner, AsyncOpenAI, OpenAIChatCompletionsModel, function_tool
from agents.run import RunConfig
from google.colab import userdata
import asyncio
import random


gemini_api_key = userdata.get("GEMINI_NEW_KEY")

if not gemini_api_key:
    raise ValueError("No Key")

external_client = AsyncOpenAI(
    api_key=gemini_api_key,
    base_url="https://generativelanguage.googleapis.com/v1beta/openai/",
)

model = OpenAIChatCompletionsModel(
    model="gemini-2.0-flash",
    openai_client=external_client,
)

config = RunConfig(
    model=model,
    model_provider=external_client,
    tracing_disabled=True
)

@function_tool
def how_many_jokes() -> int:
  return random.randint(1, 10)

async def main():
    agent = Agent(
        name="Joker",
        instructions="You are a joker. First, determine how many jokes to tell, then provide jokes.",
        tools=[how_many_jokes],
        model=model
    )

    result = Runner.run_streamed(agent, input="Hello")
    print(result)

asyncio.run(main())

